AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - Guardfile
  TargetRubyVersion: 2.3
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19
Metrics/LineLength:
  Enabled: false
